layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  include:
     projects: ucfai/team-stonks
  exclude:
    archived: true
    forks: true
    projects:

social_media:
  instagram: nspeer12
  website: http://nspeer.com
  youtube: https://www.youtube.com/channel/UCdMslK4qA_HGxWI3rQFiTMw?view_as=subscriber

topics:
  - name: Python
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1024px-Python-logo-notext.svg.png

  - name: Java
    image_url: https://icon-library.net/images/java-icon/java-icon-1.jpg

  - name: Pytorch
    image_url: https://pytorch.org/assets/images/pytorch-logo.png

  - name: NumPy
    #image_url: https://user-images.githubusercontent.com/98330/63813335-20cd4b80-c8e2-11e9-9c04-e4dbf7285aa1.png

  - name: Pandas
    #image_url: https://numfocus.org/wp-content/uploads/2016/07/pandas-logo-300.png

  - name: Matplotlib
    #image_url: https://matplotlib.org/1.3.0/mpl_examples/api/logo2.hires.png

  - name: C
   # image_url: https://www.pinclipart.com/picdir/middle/396-3965857_c-c-programming-language-logo-clipart.png
